### ISSUE TITLE
Unusable on Node < 6 due to source-map@0.7.0

### ISSUE THREAD

**Issue by kevinoid** [gulp-sourcemaps/gulp-sourcemaps#343]
Version 0.7.0 of `source-map` fails to load on Node < 6 due to `let` without `'use strict'`.  This causes the following error:

    > require('gulp-sourcemaps');
    /path/to/node_modules/source-map/lib/source-map-consumer.js:72
      let consumer = null;
      ^^^
    
    SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:387:25)
        at Object.Module._extensions..js (module.js:422:10)
        at Module.load (module.js:357:32)
        at Function.Module._load (module.js:314:12)
        at Module.require (module.js:367:17)
        at require (internal/module.js:16:19)
        at Object.<anonymous> (/tmp/node_modules/source-map/source-map.js:7:29)
        at Module._compile (module.js:413:34)
        at Object.Module._extensions..js (module.js:422:10)

  mozilla/source-map#311 has been opened, but since `source-map` declares `"node": ">= 8"` I suspect the bug is with `gulp-sourcemaps`.  I would argue that this package should depend on `"source-map": "^0.6.0"`.  If support for Node < 6 is not required, the dependency could be changed to `"source-map": "^0.7.0"` along with `"node": ">= 8"` as part of a major release of this package.

Thanks for considering,
Kevin

**Comment by gormac** [comment]
I think we might need `"source-map": "~0.6.0"` for this (tilde in stead of caret). Fixes my build. See PR #344.

**Comment by mariano-altieri** [comment]
Please make sure this fix is also propagated to versions `1.X` since it's currently breaking production projects. Thanks!

**Comment by mariano-altieri** [comment]
@nmccready - Seems like sourcemaps are back on tracks. Thank you for your quick work and response!

**Comment by phated** [comment]
@nmccready you are a much better maintainer than me.  I would have told them to upgrade to 2.x 😛

**Comment by nmccready** [comment]
> @nmccready you are a much better maintainer than me. I would have told them to upgrade to 2.x

lol, I probably would not have; but it was easy to just `git checkout v1.12.0` and make the changes and push off that without the need for a dedicated branch. Yay `git`.
