### ISSUE TITLE
Error when generating JS sourcemaps

### ISSUE THREAD

**Issue by Giovancruz** [gulp-sourcemaps/gulp-sourcemaps#370]
Hi,

Recently, when i try to run my build, the follow error occurs:
```javascript
    TypeError: resultMap.eachMapping is not a function
    at processInclude (node_modules/gulp-include/index.js:206:39)
    at processInclude (node_modules/gulp-include/index.js:193:30)
    at include (node_modules/gulp-include/index.js:58:26)
    at wrappedMapper (node_modules/map-stream/index.js:83:19)
    at Stream.stream.write (node_modules/map-stream/index.js:95:21)
    at DestroyableTransform.ondata (node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:189:13)
    at addChunk (node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:245:10)
```

Here is my gulp task:
```javascript
let sourcemaps = require("gulp-sourcemaps");

gulp.task('javascript', function (cb) {
  return pump([
    gulp.src(sourceFiles),

    sourcemaps.init(),

    /* Include custom files*/
    include({
      hardFail: true,
      extensions: ["coffee"],
      includePaths: [src]
    }).on("error", console.log),

    /* Compile coffee files*/
    coffee({ bare: true }).on("error", console.log),

    uglify().on("error", console.log),

    /* Create sourcemaps*/
    sourcemaps.write("sourcemaps"),

    gulp.dest(destination)
  ]);
});
```

Here is my env:
Node 10.15.3
NPM 6.4.1
Gulp 3.9.1 CLI & Local

I tried to update my Node to latest using NVM but other errors occurs, i think this is not the correct path. The build isnt stopped for now and the sourcemaps appear to create normally.

Anyone have idea?

**Comment by phated** [comment]
@Giovancruz your issue, as indicated by the stack trace, is within gulp-include.  This isn't a gulp-sourcemaps issue.

**Comment by Giovancruz** [comment]
Okay, anyway, no error occurs if I remove sourcemaps from my task. I'll investigate other causes. Tnks
